cart/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.CartDetailView.as_view(), name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAddView.as_view(), name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemoveView.as_view(), name='cart_remove'),
]

coupons/urls.py
from django.conf.urls import url

from coupons.views import CouponApplyView

urlpatterns = [
    url(r'^apply/$', CouponApplyView.as_view(), name='apply'),
]

myshop/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^coupons/', include('coupons.urls', namespace='coupons')),
    url(r'^', include('shop.urls', namespace='shop')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url

from orders.admin import AdminOrderDetailView, AdminOrderPDFView
from orders.views import CreateOrderView

urlpatterns = [
    url(r'^create/$', CreateOrderView.as_view(), name='order_create'),
    url(r'admin/order/(?P<order_id>\d+)/$', AdminOrderDetailView.as_view(), name='admin_order_detail'),
    url(r'admin/order/(?P<order_id>\d+)/pdf/$', AdminOrderPDFView.as_view(), name='admin_order_pdf'),

]

shop/urls.py
from django.conf.urls import url

from shop.views import ProductListView, ProductDetailView

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', ProductListView.as_view(), name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', ProductDetailView.as_view(), name='product_detail'),
]

cart/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

cart/forms.py
from django import forms

from constance import PRODUCT_QUANTITY_CHOICES


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from django.views.generic import TemplateView

from coupons.forms import CouponForm
from shop_backet import Cart
from forms import CartAddProductForm
from shop.models import Product


class CartAddView(View):
    form_class = CartAddProductForm

    def post(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        form = self.form_class(request.POST)
        if form.is_valid():
            form_cd = form.cleaned_data
            cart.add(product=product, quantity=form_cd['quantity'], update_quantity=form_cd['update'])
        return redirect('cart:cart_detail')


class CartRemoveView(View):
    def get(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
        return redirect('cart:cart_detail')


class CartDetailView(TemplateView):
    template_name = 'cart/detail.html'

    def get(self, request, *args, **kwargs):
        cart = Cart(request)
        for item in cart:
            item['update_quantity_form'] = CartAddProductForm(
                initial={'quantity': item['quantity'],
                         'update': True})
        coupon_apply_form = CouponForm()
        return render(request, self.template_name, {'cart': cart, 'coupon_apply_form': coupon_apply_form})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load i18n %}
{% load static %}

{% block title %}
  Koszyk na zakupy
{% endblock %}

{% block content %}
  <h1>Koszyk na zakupy</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Obraz</th>
        <th>Produkt</th>
        <th>Ilość</th>
        <th>Usuń</th>
        <th>Cena jednostkowa</th>
        <th>Kwota</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url "cart:cart_add" product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <input type="submit" value="Zmień">
                {% csrf_token %}
              </form>
            </td>
            <td><a href="{% url "cart:cart_remove" product.id %}">Usuń</a></td>
            <td class="num">{{ item.price }} zł</td>
            <td class="num">{{ item.total_price }} zł</td>
          </tr>
        {% endwith %}
      {% endfor %}
      {% if cart.coupon %}
      <tr class="subtotal">
        <td>Wartość całkowita</td>
        <td colspan="4"></td>
        <td class="num">{{ cart.get_total_price }} zł</td>
      </tr>
      <tr>
        <td>
          Kupon "{{ cart.coupon.code }}"
          ({{ cart.coupon.discount }}% rabatu)
        </td>
        <td colspan="4"></td>
        <td class="num neg">
          - {{ cart.get_discount|floatformat:"2" }} zł
        </td>
      </tr>
    {% endif %}
    <tr class="total">
      <td>Kwota do zapłaty</td>
      <td colspan="4"></td>
      <td class="num">
        {{ cart.get_total_price_after_discount|floatformat:"2" }} zł
      </td>
    </tr>
    </tbody>
  </table>
  {% if recommended_products %}
    <div class="recommendations cart">
      <h3>{% trans "Z tym produktem klienci kupowali również:" %}</h3>
      {% for p in recommended_products %}
        <div class="item">
          <a href="{{ p.get_absolute_url }}">
            <img src="{% if p.image %}{{ p.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
          </a>
          <p><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
        </div>
      {% endfor %}
    </div>
  {% endif %}

  <p>Kupon rabatowy:</p>
  <form action="{% url "coupons:apply" %}" method="post">
    {{ coupon_apply_form }}
    <input type="submit" value="Wprowadź">
    {% csrf_token %}
  </form>
  <p class="text-right">
    <a href="{% url "shop:product_list" %}" class="button light">Kontynuuj zakupy</a>
    <a href="{% url "orders:order_create" %}" class="button">
      Do kasy
    </a>
  </p>

    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
{% endfor %}
{% endblock %}